# Copiar este archivo como config.properties y completar con los datos reales.
# config.properties esta en el .gitignore, no se sube al repositorio.

db.host=pma.torga.com.ar
db.port=3306
db.name=s27_El Molino
db.user=u27_xm6WlzIBcR
db.password=A7fexyyjPsWaEvahL^m0J+0B
